---
title: myMCMCglmm
author: Trevor
date: '2021-04-13'
slug: mymcmcglmm
categories:
  - Models
tags:
  - R
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


```{r}
library(tidyverse)
fars_l <- read_csv("/Users/cpf/OneDrive - bjtu.edu.cn/Data/Modified/NHTSAdata/data/Output_fars/Routput_20210411_/dfpvalong.csv")
fars_l = fars_l %>% select(-c(TRAV_SP, VSPD_LIM, DR_DRINK))
# colSums(is.na(fars_l))

fars_w <- read_csv("/Users/cpf/OneDrive - bjtu.edu.cn/Data/Modified/NHTSAdata/data/Output_fars/Routput_20210411_/df_pvawide.csv")
head(fars_w)
library(MCMCglmm)

fprior = list(R = list(V = diag(2)/2, n=2),
             G = list(V = diag(2)/2, n =2)
                      )
fitfm<-MCMCglmm(cbind(INJ_SEV_1, INJ_SEV_2) ~ trait:SEX_1 + trait:SEX_2 + trait:AGE4_1 + trait:AGE4_2- 1,
             random = ~ us(trait):YRST_CASE,pr = TRUE,
             rcov = ~ us(trait):units, prior = fprior,
             family = rep("gaussian", 2),
             nitt = 20000, burnin = 10000, thin=25, data = fars_w)
lprior = list(R = list(V = 1, nu = 0.002), 
              G = list(G1 = list(V = 1, nu = 0.002), G2 = list(V = 1, nu = 0.002)))
fitfl <- MCMCglmm(INJ_SEV ~ trait: SEX + trait:AGE4 + trait:BODY_TYPE - 1,
                  random = ~ us(trait):YRST_CASE + us(trait):VEH_NO, 
                  rcov = ~ us(trait):units, prior = lprior,
                  family = "ordinal",
                  nitt = 20000, burnin = 10000, thin=25, data = fars_l)

fitmcmc <- MCMCglmm(INJ_SEV ~ SEX + REST_USE, 
                    random = ~AGE4+ VEH_NO,
                    verbose=FALSE, prior=lprior, family="ordinal",
                    nitt = 20000, burnin = 10000, thin=25, data = as.data.frame(fars_l))

fitmcmc <- MCMCglmm(INJ_SEV ~ SEX + REST_USE, random = ~ CASENUM + VENO, 
                    data = as.data.frame(dfdemo), verbose=FALSE, prior=prior, family="ordinal")

```

```{r}
library(brms)
data("kidney")
head(kidney, 3)
fitk <- brm(formula = time | cens(censored) ~ age * sex + disease + (1 + age|patient),
            data = kidney, family = lognormal(),
            prior = c(set_prior("normal(0,5)", class = "b"),
                      set_prior("cauchy(0,2)", class = "sd"),
                      set_prior("lkj(2)", class = "cor")), 
            warmup = 1000, iter = 2000, chains = 4,
            control = list(adapt_delta = 0.95))



```



```{r}

kaiyang <- read_csv("/Users/cpf/Documents/paper/Kaiyang/mywork/datagraph/car1203.csv")


```



